### ISSUE TITLE
Issue with running client script

### ISSUE THREAD

**Issue by theogf** [owulveryck/goMarkableStream#11]
Hi thanks for your work!

I tried to run the instructions (I also use the shortcut `remarkable` for the ssh so it was straightforward).
But when I run the client script I get the following error:
```
> ssh remarkable './goMarkableStreamServer.arm $(pidof xochtil)'
2021/04/29 10:42:10 Usage: ./goMarkableStreamServer.arm $(pidof xochitl)
>  RK_SERVER_ADDR=remarkable:2000 ./goMarkableClient
2021/04/29 12:42:22 listening on :8080, registered /video
press enter to take screenshot -> 2021/04/29 12:42:22 Error when calling GetImage: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup remarkable on 127.0.0.53:53: server misbehaving"
```

Am I missing something?

Forgot to mention:
Remarkable 2 - Version 2.6.2.75
Linux x64 - Ubuntu 20.04

**Comment by owulveryck** [comment]
Hi!

Did you update both the client and the server?
It looks like there is an issue with the certificate.

**Comment by theogf** [comment]
It is the first time I am using this script so I guess :)

I used : goMarkableStream_0.3.0_Linux_x86_64.tar.gz for Ubuntu and goMarkableStream_0.3.0_Linux_armv7.tar.gz for the remarkable

**Comment by theogf** [comment]
Oh wait no I got it! I was using `remarkable` as my `root@ip` and not `ip` alone. I also directly started the client from the ssh, I  think it helped.
