### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by sagnik** [owulveryck/goMarkableStream#118]
Came to this from a reddit post, have no `go` experience. 

Can't understand where to start, is there an install doc? 

The first thing it says in the _quickstart_: `localhost> ssh root@remarkable`. How to define the remarkable hostname? Do I need to be connected to the same network? Or through USB?

**Comment by sagnik** [comment]
i have two macs, one intel and the other silicon if that helps

**Comment by owulveryck** [comment]
Hello,

You can find the IP address of the remarkable in the about page (at the same place you find the root password).
Hope this helps

**Comment by sagnik** [comment]
Thanks, I have found how to connect, but I have run into #114 . Remarkable 1. I will close this issue though.
