### ISSUE TITLE
White screen only despite connection established

### ISSUE THREAD

**Issue by Utopiah** [owulveryck/goMarkableStream#23]
Hi, wondering if something in 2.10 broke streaming. Here is what I got on a `2.10.3.379` rM2 : 

```
reMarkable: ~/ ./goMarkableStreamServer.arm 
2021/12/04 15:56:07 listening on tcp :2000
2021/12/04 15:56:37 New connection from:  192.168.0.129:48916
```

and on desktop

```
fabien@fabien-CORSAIR-ONE-i160:~/Downloads$ RK_SERVER_ADDR=remarkable2:2000 goMarkableClient_0.5.2_Linux_x86_64/goMarkableClient
2021/12/04 16:56:37 listening on :8080
2021/12/04 16:56:37 Connection established
```
so it looks all fine but in the browser, a white screen. If I click on it, I can download the screenshot but then it's all white, empty to be precise as I end up with a transparent png.

Might be related to https://github.com/rien/reStream/issues/84 hence my reMarkable breaking update suspicion.

**Comment by owulveryck** [comment]
Thanks for raising this issue.
I will have a look asap.

**Comment by owulveryck** [comment]
2.10.0.234 was ok.
I am updating to check.

**Comment by Utopiah** [comment]
Let me know if I can provide any useful information to facilitate testing.

**Comment by owulveryck** [comment]
I confirm that it works with the latest version on my setup.
I will try to add extra information to investigate your problem.

Meanwhile, _have you tried turning it off and on again?_ ;)

![screenshot (47)](https://user-images.githubusercontent.com/11583401/144716633-f7e96640-ddf5-4877-bcfd-667d41fed03c.png)

**Comment by Utopiah** [comment]
Unfortunately I did but to no avail. Strangely enough everything else works, simple things like ssh or opkg, xochtil too but also more complex things like vnsee or, even stranger, reSnap.sh

**Comment by owulveryck** [comment]
I am running a custom build, I will try with the version from GitHub to see if I can reproduce.

**Comment by Utopiah** [comment]
Found the problem, once https://github.com/matteodelabre/vnsee killed, it works again. Closing the issue here and opening there, thanks for sharing and for your prompt reply!
