### ISSUE TITLE
Feature request: manual rotate

### ISSUE THREAD

**Issue by StaffanBetner** [owulveryck/goMarkableStream#24]
For some reason the autorotate functionality doesn't work for me. Might be due to the ddvk binary patch of xochitl. A workaround might be a simple manual rotate, say pressing r in the streaming endpoint.

**Comment by owulveryck** [comment]
Thanks for this issue.
The ddvk hack is preventing the autorotate to work; I will think about this feature; sounds like a good idea.

**Comment by owulveryck** [comment]
If you want, you can help me fix the autorotate with the ddvk hack:

see https://github.com/owulveryck/goMarkableStream/issues/16#issuecomment-847243924

**Comment by owulveryck** [comment]
Can I close this? Is the implémentation good enough?

**Comment by StaffanBetner** [comment]
I will close it! Good enough! I will look into providing the files for the fix as well.
