### ISSUE TITLE
connection errors

### ISSUE THREAD

**Issue by RedTartan04** [owulveryck/goMarkableStream#40]
Hi, love the new approach :) It works in general, however, I get
```reMarkable: ~/ ./goMarkableStream 
Local IP address: 192.168.178.26
2023/06/26 18:24:53 http: TLS handshake error from 192.168.178.20:53025: EOF
2023/06/26 18:24:54 http: TLS handshake error from 192.168.178.20:53026: EOF
^C
reMarkable: ~/ ./goMarkableStream 
Local IP address: 10.11.99.1
Local IP address: 192.168.178.26
2023/06/26 18:27:48 http: TLS handshake error from 10.11.99.2:53059: EOF
2023/06/26 18:27:48 http: TLS handshake error from 10.11.99.2:53060: EOF
2023/06/26 18:27:48 http: TLS handshake error from 10.11.99.2:53061: EOF
```

And it's repeatedly asking for credentials and shows "waiting for remarkable".
That's via both wifi and usb.
goMS is v 0.8.2, your binary, browser is Safari 16.5.1 on macOS 12.6.7

**Comment by RedTartan04** [comment]
edit: works fine with Firefox... so, I can live with that.

**Comment by owulveryck** [comment]
I will have a look if I have time.
Meanwhile, you can disable password authentication with `-unsafe` and/or disable HTTPS. It should do the trick (it does for iOS)
