### ISSUE TITLE
highlighter colour, rm v 2.10

### ISSUE THREAD

**Issue by RedTartan04** [owulveryck/goMarkableStream#41]
I'm still on v2.10 on the rm2, so the only colour is the highlighter = yellow.
It'll come up gray (would be ok for me, as that's what you see on the rM anyway), but thumbnails are fine (well, a little weird). Also overlayed highlighter strokes are red.
<img width="883" alt="Bildschirmfoto 2023-06-26 um 20 48 03" src="https://github.com/owulveryck/goMarkableStream/assets/99086095/fa6589c1-84e2-47fc-964a-20921c8d8ff3">
<img width="439" alt="Bildschirmfoto 2023-06-26 um 20 48 18" src="https://github.com/owulveryck/goMarkableStream/assets/99086095/d70445d8-f16b-4eff-a942-07e587bc103c">

(Firefox on macOS)

**Comment by owulveryck** [comment]
Yes, the color has changed with version 3.x.
Changing the color should be straightforward; you need to tweak the index.html file.
I won't do it because I do not want to maintain too many versions (mainly because I have very little time to work on side projects).

**Comment by RedTartan04** [comment]
Would be nice to have all your great new features in a fully 2.x compatible version, but I can understand the extra effort 😿
