### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by oren** [owulveryck/goMarkableStream#42]
Steps to reproduce:

1. Enabled wifi on rm (I am not connecting my rm with a USB. I rather use wifi)
2. curl -O https://github.com/owulveryck/goMarkableStream/releases/download/v0.8.0/goMarkableStream
3. chmod +x goMarkableStream
4. scp goMarkableStream root@10.0.0.196:
5. ssh root@10.0.0.196
6. ./goMarkableStream

expected: terminal hang
actual: terminal didn't hang. I see the cursor

Just to make sure, on my laptop, I opened http://10.0.0.196:2001 and I am 'unable to connect'

**Comment by owulveryck** [comment]
Does it do the same with the latest version ?

**Comment by oren** [comment]
I just tried on 0.8.2 and I get `./goMarkableStream: line 1: Not: command not found`. I see the same message even when running from my laptop (Ubuntu 20.10).

**Comment by owulveryck** [comment]
I updated the README with instructions to run the latest version in quickstart. Hopefully, it will help.

**Comment by oren** [comment]
Thank you. It works now but the browser (firefox and chrom) show me this after I login:

![image](https://github.com/owulveryck/goMarkableStream/assets/6517/78a8df4c-c74f-4071-8463-4b9c8bda9e9c)

**Comment by owulveryck** [comment]
Oups:
Either I messed up the commits, or it is a cache.
I will try to have a look soon, but probably not before next week.
Meanwhile, you could be able to use an older version.
Sorry about this.

**Comment by RedTartan04** [comment]
I just tried 0.9.0 and I get the same distorted image (both Firefox and Safari on Mac).
Somehow I missed all your great update so I updated straight from 0.8.2, so can't say which version introduced this issue. Let me know if I can test another 0.8.x

**Comment by owulveryck** [comment]
Oh,

This is weird because I introduced a test and I fixed a bug with the image in v0.9.0 (and I am using it without problem). 
I don't have this error.  I think it is related to the decoding process in the browser.

I just updated with the binary from the github server on my remarkable, tried with brave and safari (and my iPhone) without problem.
I will investigate.
Which firmware are you using on the reMarkable ?

**Comment by owulveryck** [comment]
And, just in case, can you try a force refresh in your browser (it is command + option + r on safari I think) ?

**Comment by RedTartan04** [comment]
Quick update between meetings: the image distortion was introduced with 0.8.6 (0.8.5 is fine). Testing with a freshly started Firefox on macOS, rM2 is still on 2.10 though (maybe later I can test with 3.5)

**Comment by owulveryck** [comment]
Since this version I am using a trivial compression algorithm to reduce bandwidth.
I can only work with firmware > 3.4 due to issue #36 (they changed the image format).
I will mention this in the readme.
Thank you for your help.

**Comment by owulveryck** [comment]
Can we close this issue ?
