### ISSUE TITLE
Need to keep connected via ash

### ISSUE THREAD

**Issue by mahondavid** [owulveryck/goMarkableStream#49]
Hi Everything works really well with this. I connect via ssh to start the service on the RM2. But if I close the cmd prompt and disconnect via ssh, it stops working. Is this the way it is intended to work? 

Great work!

**Comment by owulveryck** [comment]
Thank you.
You can add a & at the end of the./goMarkableStream:

./goMarkableStream &

The process should remain active upon deconnezion

**Comment by mahondavid** [comment]
That's sorted it thanks. This is really useful. I was never able to share my screen to my locked down work laptop before. Really great job!
