### ISSUE TITLE
rotate aspect ratio

### ISSUE THREAD

**Issue by RedTartan04** [owulveryck/goMarkableStream#51]
With my test of 0.9.0 on a rM 3.5 I noticed the aspect ratio of a rotated landscape page is still portrait (Firefox and Safari, macOS):
<img width="900" alt="Bildschirmfoto 2023-07-10 um 17 35 09" src="https://github.com/owulveryck/goMarkableStream/assets/99086095/4b1603d0-1765-4135-967a-28aae5f2935f">

Exported screeshot via button is ok.
![reMarkable](https://github.com/owulveryck/goMarkableStream/assets/99086095/aca39e20-7e48-4c53-a7bc-55b54b462d49)

**Comment by owulveryck** [comment]
This is a bug!
It is ok if you resize your window; it triggers the adapt function.
I will have a look at it.
