### ISSUE TITLE
Scrambled video

### ISSUE THREAD

**Issue by kg4zow** [owulveryck/goMarkableStream#52]
I've tried both the v0.9.0 version, and compiling it from source (from commit `eb96596d`) ... and I've tried using Brave, Firefox, and Safari on two different Macs, both connected over USB (my tablet has never connected to wifi). All cases resulted in "scrambled" video.

[Screen capture from Safari](https://jms1.pub/goMarkableStream-issue.mov)

I've seen this mentioned by a few other people, but it doesn't seem to be a wide-spread issue.

Am I missing something simple here?

**Comment by owulveryck** [comment]
I saw your comment in Reddit.
You are right, the image format has changed in recent firmware, and the new streaming process uses this new format (which gives better results for lower bandwidth).
You can use a lower version of the tool if you do not want to update.

**Comment by kg4zow** [comment]
I can't currently update the firmware on my tablet - it's brand new, and I'm still exploring what is and is not possible without connecting it to "the cloud". I *may* connect it later, but for now I'm deliberately not allowing it to even connect to wifi (which would allow software updates, and would also allow the tablet to send "telemetry", which I don't trust without knowing *exactly* what information it's sending.)

Anyway.

It might be helpful to explain the two different image formats, at the very lease which firmware versions use the old or new format, and which goMarkableStream version to use for each, in the `README.md` file.

FWIW my tablet is 3.0.5.56, which I guess we now know uses the old format. I ended up writing a little script to build executables for every tag in the repo, turns out `v0.8.5` is the last one which works with my tablet. So if nothing else, now you add a note in the `README.md` file telling people to use `v0.8.5` if their firmware "uses the old image format" (although being able to say "if your firmware is 3.x.x or earlier" would probably be more helpful).

Are there any plans for a future version of goMarkableStream to somehow *recognize* which format is being used, and adjust itself to send/receive whichever version is going to work? (Maybe if I get some time I'll dig through the code and have a go (no pun intended) at figuring this out myself.)

But like I said ... `v0.8.5` seems to be working. It shows the live screen in a browser, and the latency (from drawing a line to having it appear on the computer) over the USB-C cable seems to be less than half a second - certainly good enough for my needs.

**THANK YOU FOR WRITING THIS.**

**Comment by owulveryck** [comment]
According to #36, the format changed on FW 3.4
What has changed is the encoding is now in uint4 (only 16 "colors")

On recent version, I have first encoded two pixels in a single uint8 to reduce the amount of data to transfer 1.25Mo instead of 2.5Mo) as uint8 is the lowest unit in Go and JS.

Then, more recently, I am using an RLE algorithm to decrease the amount of data to transfer (about 175Ko).
A single uint8 stores a count of element (0 to 15) and the value.

I will blog about it when I have time, and update the readme.

Hope it helps.

**Comment by RedTartan04** [comment]
@kg4zow _> I can't currently update the firmware on my tablet - it's brand new, and I'm still exploring what is and is not possible without connecting it to "the cloud". I _may_ connect it later, but for now I'm deliberately not allowing it to even connect to wifi (which would allow software updates,_

Just to clarify:

You can switch on wifi without the rM updating its software. It's a separate setting (auto update off) you'll see once wifi is on. You can then stream goMS over wifi.

Also "the cloud" i.e. Connect is another setting independent of wifi or software update. Just don't log in in settings and your files wont sync to the cloud.

Also if you're new to the rM I'd strongly recommend to update to the latest 3.5 which has lots of issued improved. Then you could also use goMS 0.9.0, which I tested and shows no scrambled image.

**Comment by kg4zow** [comment]
@RedTartan04 Thanks for letting me know. These are the kinds of details I'm trying to figure out and document on the [`remarkable.jms1.info`](https://remarkable.jms1.info/) site.

I've noticed the tablet has a collection of "telemetry" files, which I would imagine are uploaded somewhere. Have you seen any information out there about what these files contain, when and where they're sent, and maybe if they *aren't* sent if the tablet isn't connected to a cloud account?

I ask because the one thing I *do* miss about having a network connection is NTP, but I don't like the idea of my tablet sending data *anywhere* without my knowledge.

**Comment by kg4zow** [comment]
The way it's written, 0.8.6 supports *both* versions. It probably should say ...

* version < 0.8.6 are supported on FW < 3.4
* version >= 0.8.6 are supported on FW >= 3.4

This way there's no ambiguity.
