### ISSUE TITLE
Suggestion: fixed image size

### ISSUE THREAD

**Issue by kg4zow** [owulveryck/goMarkableStream#54]
How hard would it be to add a setting which, if enabled, makes goMarkableStream always show the screen as a 1404x1872 image, without any re-sizing? This could be a new button on the slide-out panel on the left, or a command line option when running the server on the tablet.

I would find this useful for creating screenshots and videos.

**Comment by owulveryck** [comment]
I guess this is not very difficult.
But, for info, at the present time, the screenshots are already at the size of the remarkable (there is a button on the side menu).
It would only be useful for videos recording.

**Comment by kg4zow** [comment]
Yeah, I found out about screenshots already being "the right size" about ten minutes after I created this issue. All of the still screenshots I had made so far were done using RCU - I was vaguely aware of there *being* a second button on the slide-out panel but it hadn't "clicked" that the other one was for screenshots

I do kinda wish the screenshots were "rotated" to the same orientation that the stream is showing, but that's easy enough to fix after saving the file.

**Comment by owulveryck** [comment]
in v0.13, screenshots are now rotated and the size of the remarkable
