### ISSUE TITLE
Frame rate

### ISSUE THREAD

**Issue by fabianlupa** [owulveryck/goMarkableStream#55]
Hi,

I think this line is no longer valid in the readme as the environment variable RK_RATE seems to have been removed?

https://github.com/owulveryck/goMarkableStream/blob/7841e444e10f88aed77af6aa95d0197b44190c27/README.md?plain=1#L51

I was looking at increasing the frame rate as I will only use the feature over USB, therefore battery consumption is not that much of a concern. Also the release states "The consequence is that the process consumes nearly 0% CPU even when the stream is opened.", therefore I am not sure why the frame rate now is hardcoded.

**Comment by owulveryck** [comment]
I though this was useless.

I like the idea of the code to have the lowest footprint possible. I was also scared that someone set it to zero and complained about the utility making the tablet less responsive.

I will add the option back with a warning in the readme.

**Comment by fabianlupa** [comment]
Sure, frontend would be a bit more handy. Though I personally will probably just adjust the value a bit and leave it that way.

**Comment by owulveryck** [comment]
fixed in [v0.15](https://github.com/owulveryck/goMarkableStream/releases/tag/v0.15)

**Comment by fabianlupa** [comment]
Thanks!
Though I have to admit I don't see much of a subjective difference between the default and rate=100.
