### ISSUE TITLE
Landscape orientation is off by a few pixels

### ISSUE THREAD

**Issue by fabianlupa** [owulveryck/goMarkableStream#56]
When using the setting to rotate the page on the device the stream shows a few pixels on the left that should be on the right:

![image](https://github.com/owulveryck/goMarkableStream/assets/5270359/53bbf143-cd96-4890-a7e5-d5992791f21b)

![image](https://github.com/owulveryck/goMarkableStream/assets/5270359/594b77ef-3011-42fb-a6e0-545014e7af89)

**Comment by owulveryck** [comment]
Thank you.

There is not such problem on the nominal orientation?

**Comment by fabianlupa** [comment]
Now that you mention it, the normal orientation has a similar issue:

![image](https://github.com/owulveryck/goMarkableStream/assets/5270359/04d1eb6c-48f8-4261-95d3-a4007f0eabce)

**Comment by danbowes** [comment]
Hi Olivier. Congratulations on the creation of such a lightweight and effective alternative to the native screen sharing capability. My company has very strict host firewall rules so standard screen sharing to the reMarkable app doesn't work for me. Your tool works great. The only issue I have is that it doesn't seem to detect when I switch to landscape mode. I thought at first it wasn't supported yet but based on the issue raised here by @fabianlupa it looks like it is supposed to work.
Before I raise a new issue, is there something special I need to do to make it work?

<img width="1197" alt="image" src="https://github.com/owulveryck/goMarkableStream/assets/88593195/c4896e26-1e23-4878-8aa5-01f0ee1b383c">

**Comment by owulveryck** [comment]
Thank you for the kind words.

On the screen, at the left edge, there is a drop menu with a button to switch to landscape.
Hope it does the trick

**Comment by danbowes** [comment]
Perfect! Thank you. You have made my day.
For me it pops out from the left if I hover that area.

<img width="591" alt="image" src="https://github.com/owulveryck/goMarkableStream/assets/88593195/17b105a3-5f90-4568-9d7e-1b7f47851977">

**Comment by fabianlupa** [comment]
Closing as the issue is no longer present with the latest release and firmware.
