### ISSUE TITLE
Single script for starting client and server

### ISSUE THREAD

**Issue by breiting** [owulveryck/goMarkableStream#6]
Pretty nice work. I really like it. I developed a small script which allows me to start the client and the server simply from the terminal by just issuing `rmshare`. It uses `mpv` for showing the video feed.

Here is the script. Feel free to add it to your repo as well.

https://gist.github.com/breiting/6cd7d55f829bcfc88d2c46eb3a089d14

**Comment by owulveryck** [comment]
Thanks for your work.

If you want you can submit a PR with your script in a `misc/scripts` directory. Be sure to mention the OS it works on in the comment.

Olivier
