### ISSUE TITLE
Only Landscape view in Browser

### ISSUE THREAD

**Issue by Allaman** [owulveryck/goMarkableStream#63]
Hi,
first of all – thanks for this great tool! Mind-blowing, what is possible with an open system. :)

I have the issue that my remarkable is always shown in landscape view, although my notebook is in portrait mode.
<img width="1722" alt="Xnip2023-08-21_16-20-26" src="https://github.com/owulveryck/goMarkableStream/assets/12184268/4c23e9f9-a687-4be8-a1bf-21db06e96371">

Remarkable 2.14
goMarkableStream: 0.8.5 (0.8.6 causes the same [issue](https://github.com/owulveryck/goMarkableStream/issues/52))

I know that my firmware is old, but I am happy with it and don't like/need the new features. In addition, I depend on ddvk hacks and I had no time to figure out which version is supported.

Thanks!

**Comment by owulveryck** [comment]
Hi;
There is a hidden menu on the left side of the screen with a button to rotate the picture.
(I should document it or make it more visible :))

**Comment by Allaman** [comment]
Wow, thanks for the prompt response. You are (obviously) right. Now, I feel stupid 😆 

Documentation or a better visibility would help :)
