### ISSUE TITLE
Feature request: recording of stream

### ISSUE THREAD

**Issue by fahasch** [owulveryck/goMarkableStream#72]
It would be useful, to have an option to record the stream and/or transmit it to other programs such as VLC. This could be e.g. implemented via an additional button in the browser.

By the way: thanks for the excellent piece of software and the active development of it.

**Comment by owulveryck** [comment]
I am experimenting with the native features of the browser to record the stream.

This is an example of the output:

[goMarkableStreamRecording (3).webm](https://github.com/owulveryck/goMarkableStream/assets/11583401/353a6d5b-0cfb-4c36-a613-1b940a1f7527)

The video is in webm and is only 83kb.

**Comment by owulveryck** [comment]
@fahasch, if the feature is ok for you, I let you close the issue

**Comment by fahasch** [comment]
Thank you for the fast implementation. This is indeed the feature that I have been looking for.
