### ISSUE TITLE
The quality of the screen image when it is scaled down is a bit too pixelated

### ISSUE THREAD

**Issue by magv** [owulveryck/goMarkableStream#78]
Hi, Olivier. I'm trying to use goMarkableStream in zoom meetings, and there's an image quality problem I'm seeing. Basically, when you have a big canvas (1404 x 1872), but a smaller browser window, it is scaled down automatically by the browser, and the scaling is pixelated -- which looks quite a bit worse than on the tablet itself, *and* worse than the same canvas scaled down in the same browser but as an image.

Here's an example. With Firefox 115 in the goMarkableStream tab the canvas looks like this:

![on-canvas](https://github.com/owulveryck/goMarkableStream/assets/1360822/5099dcc6-42a6-4579-9ef6-2f8771e95f3d)

If I however right-click the canvas and "Open Image in another tab", the same canvas image scaled to the same size looks like this:

![on-image](https://github.com/owulveryck/goMarkableStream/assets/1360822/e11317c3-3647-4f48-8b3e-f04389dde492)

Admittedly on this small fragment the difference is not as pronounced, but it is very visible when the whole screen is shown; thin likes in drawings are particularly pixelated. That is to say, the second of these two looks quite a bit better, and I'd much prefer to have that for my usage.

I think the problem is that Firefox scales images with cubic interpolation, but not canvases -- those get faster interpolation, probably linear. (Same for Chrome too; I've checked).

I've experimented a bit and added `image-rendering: smooth` to the style of the canvas, but that changes nothing (`image-rendering: pixelated` makes it worse). There's also the [imageSmoothingQuality](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingQuality) setting of the drawing context, but setting it to `"high"` in `renderCanvas()` doesn't do anything, because both the source and the destination canvases are of the same size. So, at the moment I don't know a good way to increase the scaling quality, but I'd really like it to be increased :) Maybe you have ideas?

**Comment by owulveryck** [comment]
Thank you for raising the issue and for the investigation.
I will have a look

**Comment by owulveryck** [comment]
The point is that the resize is done via the div container in CSS.
I think you are right about the algo to be linear on resize

**Comment by owulveryck** [comment]
I am closing this issue. The latest implementation relies on WebGL and should have a better rendering
