### ISSUE TITLE
Configurable frame update period

### ISSUE THREAD

**Issue by ajmedeio** [owulveryck/goMarkableStream#79]
I think this is the definition of the frame update period of 200 ms. Perhaps we could make this configurable?

https://github.com/owulveryck/goMarkableStream/blob/1fbd2a0a7df53aad181e22e4aef6c40b134b8f98/internal/stream/handler.go#L16

**Comment by owulveryck** [comment]
I fixed this because it was a good trade-off between responsiveness and CPU usage (and therefore battery life).
I agree, this can be a parameter.
Will do it soon (adding it to the global environment configuration structure).

**Comment by owulveryck** [comment]
fixed in [v0.15](https://github.com/owulveryck/goMarkableStream/releases/tag/v0.15)
