### ISSUE TITLE
Q: Where is streamrecording saved?

### ISSUE THREAD

**Issue by RedTartan04** [owulveryck/goMarkableStream#80]
Hi, finally got round to try v13 on my v3.6 rm2. Love it :)
I just couldn't find any recording files after trying out the new feature. Where should they be and how are they named?
Running Firefox on a macOS 12.

**Comment by owulveryck** [comment]
Normally, when you stop, the recording should be downloaded automatically (so it is in my Downloads folder)
I did not test it on firefox.
