### ISSUE TITLE
Can't build on Linux (or unknown build dependencies)

### ISSUE THREAD

**Issue by jmccardle** [owulveryck/goMarkableStream#86]
Attempting to build from source. No experience building applications written with Go, I just installed `golang` on my Ubuntu (Mint) system and got this message back. So I may be missing a dependency or not have a recent enough version of the compiler.

```
$ GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build .
build github.com/owulveryck/goMarkableStream: cannot load embed: malformed module path "embed": missing dot in first path element
```

```
$ go version
go version go1.13.8 linux/amd64
```

My repo is on the v0.14 release: `commit 762f6ef1a02cef066ec328a2a14648bb35571e53 (HEAD, tag: v0.14, origin/main, origin/HEAD, main)`

Thanks for the attention.

**Comment by owulveryck** [comment]
Hello,

Your go version is too old.
You should update to 1.20 at least.

Olivier

**Comment by jmccardle** [comment]
- Downloaded `go` 1.21 from https://go.dev/dl/
- added to PATH
- had to update environment:

```
$ GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build .
go: updates to go.mod needed; to update it:
	go mod tidy
```

- that fetched some stuff, then I ran `$ GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build .` again
- success

Thanks for the help
