### ISSUE TITLE
not working after update 2.6.2.75

### ISSUE THREAD

**Issue by jpcosteira** [owulveryck/goMarkableStream#9]
Olivier, thank you for your code, made my work and my teaching a lot easier over zoom :-)

A couple of days ago I updated my remarkable2 (firmware 2.6.2.75) and ... panic ! goMarkableStream is not working...
on the client I get the following

./goMarkableClient
listening on :8080, registered /video
Error when calling GetImage: rpc error: code = Unknown desc = read /proc/218/mem: input/output error

On the remarkable I tried this
reMarkable: ~/ pid=`pidof xochitl`
reMarkable: ~/ addr=`dd if=/proc/$pid/mem bs=1 count=4 skip=4387048  2>/dev/null | hexdump | awk '{print $3$2}'`
reMarkable: ~/ skipbytes=`printf "%d" $((16#$addr))`
reMarkable: ~/ dd if=/proc/$pid/mem bs=1 count=2628288 skip=$skipbytes > out.data

--> dd: /proc/218/mem: Input/output error
and I get the message above...

there are more remarkable2's in the family, all with the previous system -I told them to reject this update- and they all work fine with the same goMarkableStream installation. Is anyone having the same issue ?

Thank you very much
Joao Costeira

**Comment by owulveryck** [comment]
Hi!
Thank you for reaching out.

I just uploaded a new version that should work with FW 2.6

Tell me if it works for you.

Olivier

**Comment by jpcosteira** [comment]
Dear Olivier,

What can I say ? Thank you very, very much...me and my students are very
grateful :-)
best regards
Joao

**Comment by oren** [comment]
I am using v0.2.1 on ubuntu 20.10 and i see the same error. the server log shows "New connection from:  10.0.0.243:58688"
