### ISSUE TITLE
Color and orientation are incorrect

### ISSUE THREAD

**Issue by Equinox4** [owulveryck/goMarkableStream#90]
The portrait mode is in a incorrect orientation (while the landscape mode is ok) and the highlighter colors are wrong.
goMarkableStream: v0.15
remarkable firmware: v3.7.0.1930
browser: firefox v119.0.1

![screenshot_remarkable2](https://github.com/owulveryck/goMarkableStream/assets/37479575/a4ea75fa-a7ba-456e-9bf1-af2e016a6e86)

**Comment by owulveryck** [comment]
I am aware of the color issue with the highlighters.
Sadly there is not much I can do about it as I a reading the colors as they are rendered on the device and colorize afterward. 
The highlight Colors are using the same value as the pen Colors.

Regarding the orientation, it is indépendant from the one on the device.
You can rotate by using the menu on the sidebar on the left (hover the mouse to make it appear)

Hope it helps

**Comment by Equinox4** [comment]
> You can rotate by using the menu on the sidebar on the left (hover the mouse to make it appear)
Oh ok, I hadn't noticed the menu on the left, I think it should be made more visible.

Too bad about the colors, I wonder how the official software displays them correctly 🤔

**Comment by Equinox4** [comment]
ok I see, it's already good to have the colors for the pens
Thank you for your answers 👍
