### ISSUE TITLE
I need to rotate always at first connect

### ISSUE THREAD

**Issue by aran1984** [owulveryck/goMarkableStream#91]
Hi,

first, great work. Love it. 

I'm not sure its a bug, but when i connect on the browser by https://IP:2001 (i have allowed non trusty content), it shows always my current VERTICAL remarkable page (i have a daily planner opened, vertical), but it shows on the browser horizontally.

If i move the cursor to the left of the page, the menu appears, i click on ROTATE one time. From here, all perfect

Can this be done so it detects if its vertial or horizontal? maybe is a default setting?

Happy to help,

I have version 3.8.2.1965 and I'm enrolled on the beta program with auto updates, i like living on the limit xD

**Comment by aran1984** [comment]
Great, that solves for me.

**https://IP:2001/?portrait=true**

By "PR is welcome", you mean for me to fork and update de readme and then create a Pull Request for you? Or how? If you guide me I can do that kindly.

**Comment by owulveryck** [comment]
Yes it is exactly what I mean.
I thought you knew how to do this, I am sorry.
I think GitHub can make your life easy. I think you can click on the readme and there might be a button for editing that will automatically create the fork and propose the PR on save.

**Comment by owulveryck** [comment]
fixed by [PR #95](https://github.com/owulveryck/goMarkableStream/pull/95)
